#!/bin/bash
# ----------------------------------------------------------------------------
# @file build
# Create a dstm package for distribution
# @author Alister Lewis-Bowen [alister@different.com]
# ----------------------------------------------------------------------------

VERSION=${1:-latest};
PACKAGE_NAME=stm_${VERSION};
TARGET=../dstm;
FILES='dstm README LICENSE';
INC_DIR=includes
INC="globals.sh help.sh misc.sh general_actions.sh profile.sh \
backup_restore.sh makefile.sh get.sh update.sh delete.sh info.sh cvs.sh \
main.sh";

rm -fR $TARGET;

cat > $TARGET <<_END_OF_HEADER_;
#!/bin/bash
# ----------------------------------------------------------------------------
# @file dstm
# Simple Drupal src tree manager
# @see color (http://code.google.com/p/ansi-color/)
# @author Alister Lewis-Bowen [alister@different.com]
# ----------------------------------------------------------------------------
# This software is distributed under the the MIT License.
#
# Copyright (c) 2008 Alister Lewis-Bowen
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.
# ----------------------------------------------------------------------------

_END_OF_HEADER_

for include in $INC; do
	cat $INC_DIR/$include >> $TARGET;
	echo >> $TARGET;
done;

cd ..;
#rm -fR *.zip *.gz;
tar -cvf ${PACKAGE_NAME}.tar $FILES;
gzip ${PACKAGE_NAME}.tar ;
zip ${PACKAGE_NAME}.zip $FILES;
