#!/bin/bash

source includes/globals.sh
source includes/help.sh
source includes/misc.sh
source includes/general_actions.sh
source includes/profile.sh
source includes/backup_restore.sh
source includes/makefile.sh
source includes/get.sh
source includes/update.sh
source includes/delete.sh
source includes/info.sh
source includes/cvs.sh
source includes/main.sh

exit 0;
